# Use the Rocky 8 Linux base image

# Update the container and install python39 python39-pip python39-devel gcc then clean all cache

# Change the working directory as /app

# Copy requirements.txt to the Container 

# Update pip via pip and Install via pip with no cache with the requirements.txt files

# Copy the entire frontend application code

# Expose the Flask port

# Command to run the Flask app via gunicorn -b 0.0.0.0:5000 app:app
